### ISSUE TITLE
Steam next fest badge & waitTime bug

### ISSUE THREAD

**Issue by Poetic-Abortionist** [TcNobo/TcNo-Mass-Steam-Idler#2]
~~The idler will not work for Steam Next Fest badge~~ (Idler works for next fest badge my mistake sorry) also the waitTime is always displayed as 5 but works with chosen number.

![image_2022-06-15_131939872](https://user-images.githubusercontent.com/32447050/173792207-4b02c05f-e107-4eef-a6a6-a823742e8b2f.png)

**Comment by TcNobo** [comment]
Haha, I was not expecting people to download this so soon. It's still VERY early in-dev. Worked late last night, and busy trying to activate 1,000 demo appids for the sale (that's how many there are). Most, however just open the Steam Store page.

Expect an update later today, as well as a guide video :)

**Comment by TcNobo** [comment]
Yeah, I grabbed a list of game demos from the current sale, and as it seems, most are not actually activating. Cleaning the list before making a video, then updated this with my changes.

**Comment by TcNobo** [comment]
Alright, the latest release has this issue fixed. A video is on the way showing how to use the program. I'll update this comment, and close this thread when it's up. https://github.com/TcNobo/TcNo-Mass-Steam-Idler/releases/tag/2022-06-15_00
