### ISSUE TITLE
SteamAPI Could Not Connect

### ISSUE THREAD

**Issue by HeavenlyDemon100** [TcNobo/TcNo-Mass-Steam-Idler#3]
Hey
I was in the middle of the idling process and got these errors:
![image](https://user-images.githubusercontent.com/107574383/173887102-6898dcba-f0c5-40ff-937c-130e68dfb471.png)

any fix?

**Comment by Poetic-Abortionist** [comment]
I am too am facing this issue.

**Comment by TcNobo** [comment]
Hey, I am brand new to using this Steamworks, and I received that error when trying to use certain App IDs. I can only assume that app 1866520 is unavailable in your region or not activated on your account, causing this issue.
See the Steam Store for more info: https://store.steampowered.com/app/1866520.

If the Download button for the demo doesn't work, as in it refreshes the page or does nothing, well, it's just a dead demo. A ton of Steam AppIDs seem to have the same issue for me, even when clicking the Download button on the official Steam Store pages.

I would assume if you'd really like, just empty `appids.txt` and leave only this one. Then run the program again, so it can activate it as well as run it.

The program runs `steam://install/1866520` to bring up the install prompt for this game.

**Comment by HeavenlyDemon100** [comment]
> Hey, I am brand new to using this Steamworks, and I received that error when trying to use certain App IDs. I can only assume that app 1866520 is unavailable in your region or not activated on your account, causing this issue. See the Steam Store for more info: https://store.steampowered.com/app/1866520.
> 
> If the Download button for the demo doesn't work, as in it refreshes the page or does nothing, well, it's just a dead demo for you. A ton of Steam AppIDs seem to have the same issue for me, even when clicking the Download button on the official Steam Store pages.
> 
> I would assume if you'd really like, just empty `appids.txt` and leave only this one. Then run the program again, so it can activate it as well as run it.
> 
> The program runs `steam://install/1866520` to bring up the install prompt for this game.
> 
> `steam://install/1866520` works for me, as well as trying to launch it using the idler.
> 
> To test this manually:
> 
> * Open `steam_appid.txt` and enter only the steam app id you want to test -- `1866520`.
> * Run `idle.exe 5000 1866520` in the install folder to launch the idler. See the result.
> 
> ![image](https://user-images.githubusercontent.com/10319195/173921038-fd55e80b-3599-4b98-9a80-7a420119c994.png)

I can download it from the store page, so no issue there.
Thanks for the fix, I'll try it if something like this happens again.
Btw, all app id's from num 52ish don't work.
Thanks again for this great tool, truly amazing stuff

**Comment by TcNobo** [comment]
It lets the user know. As for restarting at every 50, I've tried. It seems REALLY unhappy restarting for some reason or another... Launching any other console app works and opens in a separate window, but as soon as I surround it with an "if"... As in "if restart" or something, it opens as a child, and when the parent closes, so does the child >> Then it won't restart.

If anything I'll have to make another program JUST to launch the manager, and restart it. I suppose it's worth it in the long run...

I'll start work on it. I assume this software won't lose all its use after the July Next Fest.

**Comment by HeavenlyDemon100** [comment]
Gotcha. Thanks a lot for your work :)
Do you think it'll be useful to farm trading cards? Or I'm just better off with other software for that?

**Comment by TcNobo** [comment]
> am I just better off with other software for that?
Yes, it's okay with trading cards but archisteamfarm will be far more useful as it tracks cards earned, and starts and stops games at much more effective times depending on card drops

**Comment by Fanixtar** [comment]
I get this error, i have 1200 appids inside the appids.txt and it only idle game with 0 id
```Enter time to idle each game (seconds).
AUTO MODE: Idle time set to 5 seconds.
Starting idling! (1)
[1/1] Idling: , for 5 seconds...
Idling game: 0
SteamAPI could not connect.
Waiting 10 seconds, and trying again.
This game is either not activated, available, or for another reason blocked for you.

**Comment by TcNobo** [comment]
> I get this error, i have 1200 appids inside the appids.txt and it only idle game with 0 id
> ```Enter time to idle each game (seconds).
> AUTO MODE: Idle time set to 5 seconds.
> Starting idling! (1)
> [1/1] Idling: , for 5 seconds...
> Idling game: 0
> SteamAPI could not connect.
> Waiting 10 seconds, and trying again.
> This game is either not activated, available, or for another reason blocked for you.
> 

Please send the txt on github so I can recreate this issue.

**Comment by Fanixtar** [comment]
ok thanks,
[appids.txt](https://github.com/TcNobo/TcNo-Mass-Steam-Idler/files/8935780/appids.txt)

**Comment by Fanixtar** [comment]
weird, after restarting pc it's working, i'm not sure what's causing it the first time
