### ISSUE TITLE
SteamAPI could not connect

### ISSUE THREAD

**Issue by Gold14567** [TcNobo/TcNo-Mass-Steam-Idler#4]
yesterday it worked fine but now it doesn't work and says SteamAPI could not connect. After 32, it's usually a timeout.
Waiting 1 minutes, and trying again.

**Comment by Gold14567** [comment]
nvm i fixed it

**Comment by hot3ice** [comment]
> nvm i fixed it

how did you fixed it, i tried to restart steam client
